### ISSUE TITLE
Jobangebote und Praktika/2022-01-21-Werkstudent Industrial Engineering.md wird nicht angezeigt

### ISSUE THREAD

**Issue by Marlon154** [Fachschaft-FB12/Digitales-Brett#2]
@roscha444 
Sollte korrekt formatiert sein.
Ist nur Text in .md

**Comment by roscha444** [comment]
Hey @Marlon154,

thank you for issue in our repo. The date of your post was is in future, i will check the date and time format later. For now the post is online with the date from yestetday.

Greetings :wave:
